"""Pydantic models for Critic Agent and Self-Reflection Evaluation."""

from pydantic import BaseModel, Field


class CriticDimensionScore(BaseModel):
    """Score and feedback for an individual evaluation dimension."""

    dimension_name: str = Field(description="Name of evaluation dimension")
    score: int = Field(ge=0, le=25, description="Score between 0 and 25")
    max_score: int = Field(default=25, description="Maximum possible score for this dimension")
    feedback: str = Field(description="Detailed critique on strengths and weaknesses")


class CriticEvaluationReport(BaseModel):
    """Comprehensive evaluation report generated by Critic Agent."""

    total_score: int = Field(ge=0, le=100, description="Overall quality score from 0 to 100")
    is_approved: bool = Field(description="True if score >= 90 and zero severe hallucinations detected")
    dimension_scores: dict[str, int] = Field(
        default_factory=dict,
        description="Dictionary mapping dimension names to score (0-25 each)",
    )
    critique_feedback: list[str] = Field(
        default_factory=list,
        description="Key critique findings that need correction",
    )
    flagged_hallucinations: list[str] = Field(
        default_factory=list,
        description="Any fabricated technologies, skills, or exaggerated roles not present in raw CV",
    )
    actionable_improvements: list[str] = Field(
        default_factory=list,
        description="Specific instructions for the Reflector agent to fix on the next iteration",
    )
    evaluated_at_step: int = Field(default=1, description="Reflection iteration number (1, 2, 3)")


class ReflectiveSynthesisResult(BaseModel):
    """Final result of Closed-Loop Self-Reflection synthesis."""

    is_converged: bool = Field(description="True if final score achieved >= 90")
    iterations_count: int = Field(description="Total reflection rounds executed (1 to 3)")
    final_critic_score: int = Field(description="Final score awarded by Critic Agent (0-100)")
    critic_report: CriticEvaluationReport
    reflection_history: list[dict] = Field(
        default_factory=list,
        description="Step-by-step history of score improvements across iterations",
    )
